FROM openjdk:11.0.8
VOLUME /tmp
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
WORKDIR /tmp

ENTRYPOINT java -DSERVER_PORT=${SERVER_PORT} -DMONGODB_DATABASE=${MONGODB_DATABASE} -DMONGODB_HOST=${MONGODB_HOST}  -DMONGODB_PORT=${MONGODB_PORT} -DMONGODB_USERNAME=${MONGODB_USERNAME} -DMONGODB_PASSWORD=${MONGODB_PASSWORD}-jar easy-ticket-0.1.0-SNAPSHOT.jar
EXPOSE ${SERVER_PORT}
