SERVER_PORT=8080
MONGODB_DATABASE="admin"
MONGODB_HOST="localhost"
MONGODB_PORT=27017
MONGODB_USERNAME="easyadmin"
MONGODB_PASSWORD="dev1234"
VERSION="0.1.0-SNAPSHOT"

docker stop easy-ticket
docker rm --force easy-ticket

docker run aleferod/easy-ticket -d -p 27017:27017 --name=easy-ticket -e SERVER_PORT=${SERVER_PORT} -e MONGODB_DATABASE=${MONGODB_DATABASE} -e MONGODB_HOST=${MONGODB_HOST} -e MONGODB_PORT=${MONGODB_PORT} -e MONGODB_USERNAME=${MONGODB_USERNAME} -e MONGODB_PASSWORD=${MONGODB_PASSWORD}